import Link from 'next/link'

export default function Home() {
  return (
    <div className="px-4 pb-16 pt-20 text-center sm:px-6 lg:px-8 lg:pt-32">
      <h1 className="mx-auto max-w-4xl text-5xl font-medium tracking-tight text-slate-900 dark:text-slate-200 sm:text-7xl">
        Meal{' '}
        <span className="relative text-blue-600 dark:text-emerald-400">
          Tracking
        </span>{' '}
        made simple with the help of{' '}
        <span className="relative text-blue-600 dark:text-emerald-400">AI</span>
        !
      </h1>
      <p className="mx-auto mt-6 max-w-2xl text-lg tracking-tight text-slate-700 dark:text-slate-100">
        Have your meal plans generated by artificial intelligence based on your
        needs and track your meals to follow your progress.
      </p>
      <div className="mt-10 flex justify-center">
        <Link
          href="/login"
          className="rounded-md bg-black px-4 py-3 text-sm font-semibold text-white shadow-sm"
        >
          Get Started
        </Link>
      </div>
    </div>
  )
}
